/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cs490.boom;

import java.util.ArrayList;

/**
 *
 * @author mtdtao
 */
public class MusicPanel extends javax.swing.JPanel {

    private int musicIndex = -1;
    //public static String[] myMusicList;
    public static ArrayList<String> myMusicList = new ArrayList<String>();
    /**
     * Creates new form MusicPanel
     */
    public MusicPanel() {
        initComponents();
//        myMusicList = new String[3];
//        my
//        myMusicList[0] = "first";
//        myMusicList[1] = "hello";
//        myMusicList[2] = "third";
        myMusicList.add("first");
        myMusicList.add("helo");
        myMusicList.add("third");
        
        musicList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = myMusicList.toArray(new String[myMusicList.size()]);
            public int getSize() { return myMusicList.size(); }
            public String getElementAt(int i) { return myMusicList.get(i); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        musicList = new javax.swing.JList<>();
        addMusicButton = new javax.swing.JButton();

        musicList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                musicListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(musicList);

        addMusicButton.setText("add music");
        addMusicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMusicButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMusicButton)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addMusicButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addMusicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMusicButtonActionPerformed
        // TODO add your handling code here:
        //DefaultListModel model = new DefaultListModel();
        System.out.println("you click a button");
        AddMusicPopUp pop = new AddMusicPopUp();
        pop.setLocationRelativeTo(null);
        pop.setVisible(true);
        
        for (int i = 0; i < myMusicList.size(); i++) {
            System.out.println(myMusicList.get(i));
        }
        
        if (musicIndex < 0) {
            System.out.println("select index");
            
        } else {
            //JOptionPane.showMessageDialog(jButton1, "click");
            //myMusicList[musicIndex] = "this has changed";
            musicList.updateUI();
        }
        
    }//GEN-LAST:event_addMusicButtonActionPerformed

    private void musicListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_musicListValueChanged
        // TODO add your handling code here:
        if (evt.getValueIsAdjusting()) {
            String value = (String) musicList.getSelectedValue();
            musicIndex = musicList.getSelectedIndex();
            System.out.println("you click a button "+value+" and index is "+musicIndex);
        }
        
    }//GEN-LAST:event_musicListValueChanged

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMusicButton;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JList<String> musicList;
    // End of variables declaration//GEN-END:variables
}
