/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cs490.boom;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.CannotRealizeException;
import javax.media.ControllerEvent;
import javax.media.ControllerListener;
import javax.media.Manager;
import javax.media.NoPlayerException;
import javax.media.Player;
import javax.media.RealizeCompleteEvent;
/**
 *
 * @author Len
 */
public class VideoPlayerGUI extends javax.swing.JPanel implements ActionListener, ControllerListener{
    
    public Player player;
    private File file;
    /**
     * Creates new form VideoPlayerGUI
     */
    public VideoPlayerGUI() {
        initComponents();
        openFile("F:\\hc2.avi");

    }
    
    /**
     *
     * @param name file name of the a video file
     */
    public void openFile(String name) {
        file = new File(name);
        if (file.exists()) {
            try {
                player = Manager.createRealizedPlayer(file.toURI().toURL());
                player.addControllerListener(this);
                player.start();
                player.realize();
            } catch (Exception ex) {
                Logger.getLogger(VideoPlayerGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void controllerUpdate(ControllerEvent ce) {
        if (ce instanceof RealizeCompleteEvent) {
            Component visual = player.getVisualComponent();
            
            if (visual != null) {
                this.add(visual, BorderLayout.CENTER);
            }
            Component control = player.getControlPanelComponent();
            if (control != null) {
                this.add(control, BorderLayout.SOUTH);
            }
            this.doLayout();;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
